<?php

use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 * @var \TrueLayer\Connect\Block\Checkout\PaymentErrorMessage $block
 */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "truelayer-error-message": {
                        "component": "TrueLayer_Connect/js/clear_payment_error_message",
                        "hasError": <?= $block->hasMessage() ? 'true' : 'false' ?>,
                        "errorMessage": "<?= $escaper->escapeHtml(__($block->getMessage())) ?>"
                    },
                    "truelayer-pending": {
                        "component": "TrueLayer_Connect/js/cart_refresh"
                    }
                }
            }
        }
    }
</script>
