<?php

use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 * @var \TrueLayer\Connect\Block\Checkout\PaymentErrorMessage $block
 */
?>

<span id="truelayer-payment-error-message" class="truelayer-payment-error message error" data-bind="scope:'truelayer-error-message',visible:false">
    <?=$escaper->escapeHtml(__($block->getMessage()));?>
</span>

<script type="text/x-magento-init">
    {
        ".truelayer-payment-error": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "truelayer-error-message": {
                        "component": "TrueLayer_Connect/js/clear_payment_error_message",
                        "hasError": <?= $block->hasMessage() ? 'true' : 'false' ?>,
                        "errorMessage": "<?= $block->getMessage() ?>"
                    }
                }
            }
        }
    }
</script>
