<?php

use Magento\Framework\Escaper;
use TrueLayer\Connect\Block\Checkout\PaymentErrorMessage;

/**
 * @var Escaper $escaper
 * @var PaymentErrorMessage $block
 */
?>

<?php
$message = $block->getMessage();
$errorMessage = is_null($message) ? 'null' : ('"'.$escaper->escapeHtml(__($message)).'"');
$hasError = is_null($message) ? 'false' : 'true';
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "truelayer-error-message": {
                        "component": "TrueLayer_Connect/js/payment_error_message",
                        "hasError": <?= $hasError ?>,
                        "errorMessage": <?= $errorMessage ?>
                    }
                }
            }
        }
    }
</script>
