<?php
/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block Magento\Framework\View\Element\Template */
/** @var $viewModel TrueLayer\Connect\ViewModel\Checkout\Pending */
$viewModel = $block->getData('view_model');
?>
<div class="checkout-pending" data-bind="scope:'truelayer-pending'">
    <h2>
        <?= $block->escapeHtml(__('Your payment has been accepted by your bank.')) ?>
        <br />
        <?= $block->escapeHtml(__(
            'We are redirecting you to the order confirmation page but it might take an extra second.'
        )) ?>
    </h2>

    <div class="truelayer-loading" data-bind="visible: isShowLoader" style="display: none;">
        <div class="loading-container">
            <div class="loading"></div>
            <div class="progress"></div>
        </div>
    </div>

    <div class="truelayer-result">
        <div class="message success" data-bind="visible: isSuccess" style="display: none;">
            <div>
                <?= $block->escapeHtml(__('Success! You will now be redirected to another page.')) ?>
            </div>
        </div>
        <div class="message info" data-bind="visible: isError" style="display: none;">
            <div>
                <?= $block->escapeHtml(__('Your payment is being processed by your bank.')) ?>
                <?= $block->escapeHtml(__('Please wait for an order confirmation email.')) ?>
            </div>
        </div>
    </div>
</div>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>

<script type="text/x-magento-init">
        {
            ".checkout-pending": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "truelayer-pending": {
                            "component": "TrueLayer_Connect/js/pending",
                            "config": {
                                "refreshUrl": "<?= $block->escapeUrl($viewModel->getRefreshUrl()) ?>",
                                "checkUrl": "<?= $block->escapeUrl($viewModel->getCheckUrl()) ?>"
                            }
                        }
                    }
                }
            }
        }
</script>
