<?php

/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Framework\View\Element\Template */
?>

<div class="truelayer-checkout-pending" data-bind="scope:'truelayer-pending'">
    <h2>
        <?=$block->escapeHtml(__('Please wait, we are processing your payment'))?>
    </h2>

    <div class="truelayer-loading">
        <div class="loading-container">
            <div class="loading"></div>
            <div class="progress"></div>
        </div>
    </div>
</div>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>

<script type="text/x-magento-init">
    {
        ".truelayer-checkout-pending": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "truelayer-pending": {
                        "component": "TrueLayer_Connect/js/pending"
                    }
                }
            }
        }
    }
</script>