<?php

/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Framework\View\Element\Template */
/** @var $escaper Magento\Framework\Escaper */
?>

<div class="truelayer-checkout-pending" data-bind="scope:'truelayer-pending'">
    <h2 data-bind="visible: isLoading">
        <?=$escaper->escapeHtml(__('Please wait, we are processing your payment'))?>
    </h2>

    <div class="truelayer-loading" data-bind="visible: isLoading">
        <div class="loading-container">
            <div class="loading"></div>
            <div class="progress"></div>
        </div>
    </div>

    <div class="message info" data-bind="visible: isError" style="display: none;">
        <div>
            <?=$escaper->escapeHtml(__('Your payment is taking longer than usual to authorize.'))?>
            <?=$escaper->escapeHtml(__('Please wait for an order confirmation email.'))?>
        </div>
    </div>
</div>
<?php // phpcs:ignore Magento2.Legacy.PhtmlTemplate ?>

<script type="text/x-magento-init">
    {
        ".truelayer-checkout-pending": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "truelayer-pending": {
                        "component": "TrueLayer_Connect/js/pending"
                    }
                }
            }
        }
    }
</script>