<?php
/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

use TrueLayer\Connect\Block\Adminhtml\System\Config\Button\Credentials;

/**
 * @see \TrueLayer\Connect\Block\Adminhtml\System\Config\Button\Credentials
 * @var Credentials $block
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        let private_key_sandbox = '',
            private_key_production = '',
            truelayer_mode = 'sandbox';

        document.querySelector('#truelayer_general').addEventListener('change', (e) => {
            // Check mode
            if (e.target.getAttribute('name').includes('[mode]')) {
                truelayer_mode = e.target.value;
            }

            if (e.target.getAttribute('type') === 'file') {
                const FR = new FileReader();

                FR.onload = () => { 
                    truelayer_mode === 'sandbox' 
                        ? private_key_sandbox = FR.result 
                        : private_key_production = FR.result;
                }

                FR.readAsText(e.target.files[0], "UTF-8");
            }
        });

        var resultSpan = jQuery('#result_api');
        jQuery('#truelayer-button_credentials').click(function () {
            var params = {
                "production_client_id":
                    jQuery("input[name='groups[general][fields][production_client_id][value]']").val(),
                "production_client_secret":
                    jQuery("input[name='groups[general][fields][production_client_secret][value]']").val(),
                "production_key_id":
                    jQuery("input[name='groups[general][fields][production_key_id][value]']").val(),
                "sandbox_client_id":
                    jQuery("input[name='groups[general][fields][sandbox_client_id][value]']").val(),
                "sandbox_client_secret":
                    jQuery("input[name='groups[general][fields][sandbox_client_secret][value]']").val(),
                "sandbox_key_id":
                    jQuery("input[name='groups[general][fields][sandbox_key_id][value]']").val(),
                "mode":
                    jQuery("select[name='groups[general][fields][mode][value]']").val(),
                "private_key": truelayer_mode === 'sandbox' ? private_key_sandbox : private_key_production,
            };

            new Ajax.Request('<?= $block->escapeUrl($block->getApiCheckUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find('.connecting').hide();
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        var json = response.responseJSON;
                        if (typeof json.msg != 'undefined') {
                            resultText = json.msg;
                            jQuery("input[name='groups[connection][fields][account][value]']").val(json.account)
                        }
                    }

                    resultSpan.find('.result').show();
                    resultSpan[0].querySelector('.result').textContent = resultText;
                }
            });
        });
    });
</script>

<div class="check-credentials-wrapper">
    <?= $block->getButtonHtml() ?>
    <div id="result_api">
        <span class="connecting" style="display: none;">Connecting...</span>
        <span class="result"></span>
    </div>
</div>
