<?php
/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

use TrueLayer\Connect\Block\Adminhtml\System\Config\Button\DebugCheck;

/**
 * @see \TrueLayer\Connect\Block\Adminhtml\System\Config\Button\DebugCheck
 * @var DebugCheck $block
 */
?>
<div id="tl-result_debug-modal" data-tl-endpoind-url="<?= $block->escapeUrl($block->getDebugCheckUrl()) ?>">
    <div id="tl-result_debug">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>
