<?php
/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 */

use TrueLayer\Connect\Block\Adminhtml\System\Config\Button\ErrorCheck;

/**
 * @see \TrueLayer\Connect\Block\Adminhtml\System\Config\Button\ErrorCheck
 * @var ErrorCheck $block
 */
?>
<div id="mm-ui-result_error-modal" data-mm-ui-endpoind-url="<?= $block->escapeUrl($block->getErrorCheckUrl()) ?>">
    <div id="mm-ui-result_error">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>
