<?php
/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var \TrueLayer\Connect\Block\Adminhtml\Design\Header $block
 */
$logo = $block->getViewFileUrl('TrueLayer_Connect::images/logo-expanded.svg');
?>
<div class="tl-header">
    <img class="tl-logo" src="<?=$block->escapeUrl($logo);?>" width="215" alt="TrueLayer" />

    <div class="tl-header-cols">
        <div class="tl-header-text">
            Transform your payment method from a cost center into a growth enabler.
            <br />
            Easily integrate our simpler, faster, and seamless payments into your website or app.
        </div>

        <a class="tl-header-action tl-btn tl-btn-secondary tl-btn-lg" href="https://support.truelayer.com/hc/en-us/requests/new" target="_blank" rel="noopener">
            <?= $block->escapeUrl(__('Get in touch')); ?>
        </a>
    </div>
</div>
