<?php
/**
 * Copyright © TrueLayer Ltd. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var \TrueLayer\Connect\Block\Adminhtml\Design\Header $block
 */
?>
<div class="mm-truelayer-header">
    <div class="mm-truelayer-header-icon">
        <p>TRUELAYER</p>
    </div>
    <div class="">
        <p class="mm-truelayer-header-text">
            Easily integrate next-generation payments and financial data
            into any app. Build powerful products your customers love.
        </p>
    </div>
    <div class="mm-truelayer-header-actions">
        <a id="mm-truelayer-button_help" class="helpbutton" href="mailto:contact@magmodules.eu"
           target="_blank">
            <span><?= $block->escapeUrl(__('Get in Touch')); ?></span>
            <i class="mm-truelayer-icon__arrow-right"></i>
        </a>
    </div>
</div>
