name: Check config.xml version
on:
  push:
    branches:
      - 'feature/PLUG-155'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set OLD_VERSION from etc/config.xml if merge would modify it
        run: |
              echo "OLD_VERSION=$(git log origin/main..HEAD --cherry -p -- etc/config.xml | grep '\-.\s*.\<version\>' | tail -1 | tr -d '\-[:blank:]\n' | sed -e 's/<version>\(.*\)<\/version>/\1/')" >> $GITHUB_ENV

      - name: Set NEW_VERSION from etc/config.xml if merge would modify it
        run: |
              echo "NEW_VERSION=$(git log origin/main..HEAD --cherry -p -- etc/config.xml | grep '\+.\s*.\<version\>' | head -1 | tr -d '+[:blank:]\n' | sed -e 's/<version>\(.*\)<\/version>/\1/')" >> $GITHUB_ENV

      - name: Test that versions are not empty
        run: |
              [[ ! -z $OLD_VERSION ]] && [[ ! -z $NEW_VERSION ]]

      - name: Test that versions are different
        run: |
              [[ $OLD_VERSION != $NEW_VERSION ]]

      - name: Print versions
        run: |
              echo "Old version: ${OLD_VERSION:-unknown}; New version: ${NEW_VERSION:-unknown}"