name: Check config.xml version
on:
  push:
    branches:
      - 'feature/PLUG-155'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Compare version
        run: |
              [[ "v$(cat ./etc/config.xml | grep \<version\> | sed -e 's/<version>\(.*\)<\/version>/\1/' | tr -d '[:blank:]')" == $(git describe --tags --abbrev=0 | tr -d '\n') ]]
