name: Check config.xml version
on:
  push:
    branches:
      - 'feature/PLUG-155'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Compare version
        run: |
              [[ "v$(xmlstarlet sel -t -v '//config/default/payment/truelayer/version' ./etc/config.xml)" == $(git describe --tags --abbrev=0 | tr -d '\n') ]]
